apiVersion: v1
kind: Service
metadata:
  name: first-app-service
  namespace: first-app
  labels:
    app: first-app
spec:
  selector:
    app: first-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80